import type { Aspect } from './aspect'

export type NodeId = string
export type SourceId = string

/**
 * Scarce by design. Four in v1; a sixth requires a written case.
 *
 * `sequence` is the fifth, and the written case was made before it was built:
 * `build-plan.md` reserves this slot for it by name, listing the groundwork
 * that was laid for it in v1 — clips normalised on arrival, `duration_ms`/`fps`
 * /`codec` on assets, and `position` on edges, which is where a cut's order
 * lives because every other node treats its inputs as a set.
 */
export type NodeType = 'source' | 'image' | 'video' | 'export' | 'sequence'

export type AssetRef = {
  id: string
  path: string
  mime: string
  width?: number
  height?: number
  durationMs?: number
  fps?: number
  codec?: string
}

/**
 * What a placement will accept. Every field is a rejection somebody would
 * otherwise get back from a client, a week later, with the buy already booked.
 */
export type FormatSpec = {
  /** Fractions of the frame that must stay clear of text — UI chrome sits there. */
  safeZone: { top: number; right: number; bottom: number; left: number }
  /**
   * Fractions of the frame the source must already cover. Defaults to 1: the
   * source is never upscaled to fill a placement, because upscaled output looks
   * like a cheap ad and no amount of prompt work fixes it.
   */
  minScale: number
  maxDurationSec: number
  /** Fraction of the frame text may cover. */
  maxTextCoverage: number
}

export type AdFormat = {
  name: string
  w: number
  h: number
  /** Per-format overrides. See DEFAULT_FORMAT_SPEC. */
  spec?: Partial<FormatSpec>
}

/** Fractions of the frame. Declared, not detected — see core/spec.ts. */
export type TextBox = { x: number; y: number; w: number; h: number }

/**
 * Headline and CTA composited into the exported file, not generated by the
 * model.
 *
 * This is what makes safe-zone and text-coverage checks arithmetic instead of
 * OCR: the box is declared, so its position is known before a pixel is drawn.
 * Text burned in by an image model is still possible and simply goes unchecked.
 */
export type TextOverlay = {
  headline?: string
  cta?: string
  box?: TextBox
}

/**
 * Canvas coordinates. Stored in `graph_json` so a reload does not scramble the
 * layout, and deliberately excluded from the input hash — see core/hashable.ts.
 */
export type NodePosition = { x: number; y: number }

/**
 * How large the card is drawn. Canvas coordinates like `position`, and excluded
 * from the input hash by the same whitelist — dragging a corner to see a shot
 * bigger must never invalidate it and re-bill everything downstream.
 */
export type NodeSize = { w: number; h: number }

type NodeBase = {
  id: NodeId
  /**
   * Optional so a hand-written flow file (`flows/demo.json`, the headless
   * runner) never has to invent coordinates. The canvas assigns one on create
   * and falls back to an auto-layout when it is missing.
   */
  position?: NodePosition
  /** Optional for the same reason as `position`. The canvas has a default. */
  size?: NodeSize
  /** View-only. Never hashed. */
  label?: string
}

/**
 * A reference to a row in the project's `sources` table — not the file itself.
 *
 * The indirection is what keeps one product usable across several campaigns:
 * replace its files, and every shot downstream of it, in every flow, goes stale.
 */
export type SourceNode = NodeBase & {
  type: 'source'
  sourceId: string
}

export type ImageNode = NodeBase & {
  type: 'image'
  prompt: string
  /**
   * A row in the model catalog, by id. The node decides; nothing overrules it.
   *
   * It replaced `modelRole: 'draft' | 'hero' | 'specialist'`, which named a slot
   * rather than a model and was overridden wholesale by a toolbar toggle — so
   * three nodes wired to one product photo could not run on three models, which
   * is the comparison that decides which model is worth paying for.
   */
  modelId: string
  seed?: number
  /**
   * The shape it renders at. Absent means 1:1, which is what every endpoint did
   * before anyone could ask for anything else — so an existing flow reads the
   * same after this field arrived as it did before.
   *
   * Deliberately not on a clip: a clip's shape comes from the still it starts
   * from, and a second declaration here could only ever disagree with it.
   */
  aspect?: Aspect
}

export type VideoNode = NodeBase & {
  type: 'video'
  prompt: string
  durationSec: number
  audio: boolean
  /** A row in the model catalog, by id. See ImageNode.modelId. */
  modelId: string
  seed?: number
}

export type ExportNode = NodeBase & {
  type: 'export'
  /**
   * Empty means "the project's formats". `exportFlow` no longer resolves this
   * itself — a download names its own `formats` — so it is the transitional
   * route at `/api/export` that still reads this field and falls back to the
   * project's, until this node is deleted.
   */
  formats: AdFormat[]
  fps?: number
  codec?: string
  overlay?: TextOverlay
}

/**
 * Several clips, cut into one film, in order.
 *
 * Carries no configuration of its own on purpose. The order is the whole
 * content of this node and it lives on the incoming edges' `position`, because
 * an ordering stored twice is an ordering that will disagree with itself.
 *
 * It dispatches to no model. It is planned and run like any other node — cut
 * locally by the worker, not at export — and costs nothing because its clips
 * have already been paid for.
 */
export type SequenceNode = NodeBase & {
  type: 'sequence'
}

export type FlowNode = SourceNode | ImageNode | VideoNode | ExportNode | SequenceNode

/**
 * Edges carry meaning. An image → video edge with `role: 'start_frame'`
 * literally means "this image is frame zero of that clip", and the registry's
 * `caps.startEndFrame` gates it at wiring time rather than silently ignoring
 * it at render time.
 */
export type Edge = {
  id: string
  from: NodeId
  to: NodeId
  role: 'reference' | 'start_frame' | 'end_frame' | 'input'
  /** Reserved for v2 sequence ordering. Always null in v1. */
  position: number | null
}

export type Flow = {
  nodes: FlowNode[]
  edges: Edge[]
}

/** The minimum a graph walk needs. Lets the walks stay independent of node shape. */
export type GraphShape = {
  nodeIds: NodeId[]
  edges: Edge[]
}
